{% set name = "html-tag-names" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/html-tag-names-{{ version }}.tar.gz
  sha256: 04924aca48770f36b5a41c27e4d917062507be05118acb0ba869c97389084297

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - HtmlTagNames
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Riverside-Healthcare/html-tag-names
  summary: List of known HTML tag names
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
